Net 447 SLP-03: Adjust ticket block check
dn3010/sylo-ethereum-contracts pull request #102
Opened 2023-02-16 00:18 UTC by JCSanPedro

## Motivation

The audit noted that it was possible for a ticket to be redeemed with a generation block greater than the current epoch's end block.

This PR prevents that by additionally checking if the ticket generation block is less than or equal to than the current block.

## Summary of Changes

- Add additional check for ticket generation block
- Remove require check that the ticket generation block is within the current epoch in the `redeem` function. This is because we also perform the same check in `calculateWinningProbability`, so it is unnecessary to do here as well.

2023-02-16 22:46 UTC, JoshD641 requested changes
The code change LGTM. At first I thought it was odd to remove the check from `redeem` rather than from `calculateWinningProbability`, and spread out the checks unnecessarily, but it does makes sense in the context of the ticket win probability decay to do it inside `calculateWinningProbability`.

We should probably leave the old test case in place, rather than editing it, to make sure that the require inside `calculateWinningProbability` is working too.

2023-02-16 23:01 UTC, JCSanPedro commented
> We should probably leave the old test case in place, rather than editing it, to make sure that the require inside calculateWinningProbability is working too

There is another test case that already exists for that function specifically https://github.com/dn3010/sylo-ethereum-contracts/blob/master/test/payments/ticketing.ts#L414-L435

2023-02-16 23:06 UTC, JoshD641 approved these changes

2023-02-20 00:06 UTC, teinnt commented on contracts/Payments/Ticketing.sol
>          require(epoch.startBlock > 0, "Ticket's associated epoch does not exist");
Do we want to remove the check here, because this will be checked again in `calculateWinningProbability`?

2023-02-20 00:26 UTC, JCSanPedro commented on contracts/Payments/Ticketing.sol
>          require(epoch.startBlock > 0, "Ticket's associated epoch does not exist");
Makes sense

2023-02-20 01:19 UTC, teinnt approved these changes

2023-02-20 01:19 UTC, merged