NET-444 Optimise event ticket validation in notify events
dn3010/sylo-ethereum-contracts pull request #120
Opened 2023-02-21 22:43 UTC by Helenpham1097

## Motivation

When the node is requested to do a relay, it should check the sender's deposit in advance to eliminate from being attacked related to front-running because the sender might request a relay and then preemptively withdraws their funds (after unlocking) to avoid paying the node.

However, the node currently has not checked senders' deposit each time a relay is requested. This is because making a call to the blockchain each relay request is prohibitively expensive (in terms of API call rate limit, not gas). 

The fact that the node should not need to query each sender’s escrow more than one per unlockDuration that could help to reduce the on-chain workload load by reducing the required query rate.

**Case 1:** 
If the node knows that a sender is not unlocking at the block it receives the request (eg named as received_block), then it can be assured that the sender's deposit would present until _received_block + unlockDuration_. In addition, the deposit needs to be kept for the entire valid duration of one relay (ticket duration). This means that the node can rely on that escrow before _received_block  +  unlockDuration - ticketDuration_ without needing to check the escrow on-chain.

**Case 2:**
If the senders' deposits are in unlocking process at at the block it receives the request (eg named as received_block), and will finish unlocking at time unlockAt, then the node can safely rely on the senders' deposits for relays requested before block _unlockAt  - ticket_duration_.

**Case 3:**
However, there is another case we should consider when the network parameters would be changed that negatively affect the logic of ticket validation. These parameters may be ticket_duration and unlock_duration because these formulas are based on the two values which might be updated by owners.

For example, if we make the lock duration longer than the current one, then it’s not a problem, but if we shorten them there’s a window where exploitation is possible when nodes follow this policy. Therefore, we need to subscribe to unlock duration update event and ticket duration update events. This way can keep the node safe and change the policy immediately once any update event happens.

**Case 4:** 
There is another case that we should consider when the sender does not have insufficient escrow anymore, and then its penalty has been slashed by other node that our current node does not know as the current node depends on sender's deposit on its own cache. Therefore, the node might continue to accept the sender's relay which is wrong. Therefore, we should have an event when senders' penalties are burnt which can helps all nodes subscribing to this event can recognise bad sender, and update their own cache to evoid being exploited by senders

## Summary of changes

- add event when sender's penalty is burned

2023-03-01 01:08 UTC, JCSanPedro requested changes

2023-03-01 01:08 UTC, JCSanPedro commented on contracts/Payments/Ticketing.sol
> +    error RedeemerCommitMismatch();
Should remove these whitespace additions from the PR

2023-03-01 01:08 UTC, JCSanPedro commented on contracts/Payments/Ticketing.sol
> +        uint256 callUnlockAt; //Block number a user call unlock
What is this field used for?

2023-03-01 02:02 UTC, Helenpham1097 commented on contracts/Payments/Ticketing.sol
> +        uint256 callUnlockAt; //Block number a user call unlock
@JCSanPedro Hi John, I just add explanation in the PR message. Please have a look at this. Thank you

2023-04-03 21:36 UTC, JCSanPedro approved these changes

2023-04-16 21:38 UTC, merged