NET-552 Add receiver signature when redeem ticket
dn3010/sylo-ethereum-contracts pull request #135
Opened 2023-05-17 04:25 UTC by teinnt

Currently the ticket redemption process is protected by having the receiver decrypt a portion of the ticket, then returning that portion to the relay node. This problems with this process is outlined here [https://www.notion.so/futureverse/e34604acc8ad423e88da2d3de438a668?v=6acf6334375c4c698c7f97bbb8f84508&p=c4 bed91907b348d7a4c46cd885b5665a&pm=s](https://www.notion.so/futureverse/e34604acc8ad423e88da2d3de438a668?v=6acf6334375c4c698c7f97bbb8f84508&p=c4bed91907b348d7a4c46cd885b5665a&pm=s)

This task involves adding an additional field to the ticket structure to indicate the receiver’s signature.

2023-05-19 02:44 UTC, JCSanPedro requested changes
Good work 👍

2023-05-19 02:44 UTC, JCSanPedro commented on contracts/interfaces/payments/ISyloTicketing.sol
> +        address receiverDelegatedAccount; // Address of the ticket's signer if not the original receiver (optional)
I think we can create a specific type that wraps a user and their delegated account.

```
struct User {
  address main;
  address delegated;
}
```

Can define in `ISyloTicekting.sol` for now

2023-05-19 02:44 UTC, JCSanPedro commented on contracts/payments/SyloTicketing.sol
> +            ) {
I think we can wrap this logic in a function
```
function hasValidDepositPermission(User user) internal (bool) {
  ...
}
```

2023-05-19 02:44 UTC, JCSanPedro commented on contracts/payments/SyloTicketing.sol
> +            )
DId you run prettier? Maybe just also seperate the args in the call `isValidTicketSig(senderSig, ticket.sender, ticket.senderDelegatedAccount, ticketHash)` so we have format consistency? Unless prettier is doing this automatically

2023-05-19 03:08 UTC, teinnt commented on contracts/payments/SyloTicketing.sol
> +            )
Yeah, this one is auto reformatter by Prettier, because the length is longer than the default length.

2023-05-19 05:08 UTC, teinnt commented on contracts/payments/SyloTicketing.sol
> +        address receiver,
The maximum event index is 3 so we cannot have `receiver` as an indexed parameters.

2023-05-22 21:13 UTC, JCSanPedro commented on contracts/payments/SyloTicketing.sol
> +            revert ReceiverDelegatedAccountDoesNotHaveWithdrawalPermission();
I'm thinking `DepositWithdrawal` isn't the best name now that we have the receiver signature as well.

Maybe change to `TicketSigning`?

2023-05-22 21:13 UTC, JCSanPedro commented on contracts/payments/SyloTicketing.sol
> +                ticketHash
I think we can replace these two parameters with just one `User` parameter

2023-05-22 21:16 UTC, JCSanPedro commented on test/payments/ticketing.test.ts
> +        alice,
I think for the tests we should create a different account for the receiver

2023-05-29 21:52 UTC, JCSanPedro submitted a review, later dismissed
Good work 👍 .

@JoshD641 can you review please.

2023-05-29 22:33 UTC, JoshD641 submitted a review, later dismissed
The code changes look good to me =)

This might be related to a different PR - It'd be good to record the conversations we've had about blacklisting, and whether the node can force tickets to win by setting the rand, on notion. Moving away from using the sender's rand, to using the receiver signature, in the ticket logic is a fairly big change, and writing down the implications of that change will be good context for later. 

It might makes sense to update and extend this doc, which currently refers to a version of the code that uses both rands: https://www.notion.so/futureverse/RFC-Avoiding-reliance-on-asymmetric-encryption-for-protecting-ticket-redemptions-c4bed91907b348d7a4c46cd885b5665a

(I can have a go at it if you think it's a good idea @JCSanPedro )

2023-06-08 02:28 UTC, JoshD641 reviewed
The PR looks good as far as I can see - I identified issues around comments and readability, and the tests cover every case I could think of. The only reason this isn't an "approve" review is related to my question in the comment on the tests - in case that creates a situation where the test isn't testing what we think it is.

2023-06-08 02:28 UTC, JoshD641 commented on contracts/AuthorizedAccount.sol
> +                        if (authorizedAt <= atBlock && atBlock < unauthorizedAt) {
I think this section could be expressed in a way that's easier to read. 

It seems to be correct, but the logic relies on the default value of unauthorisedAt, which made it harder to understand what idea the checks were capturing conceptually without jumping around the code.

Maybe something like this?

if (wasUnAuthorisingAtBlock || wasAuthorisedAtBlock ){
return true
}

Where those bools are calculated separately on earlier lines (using the same logic you've used in the two if statements), would make it a bit faster to read.

2023-06-08 02:28 UTC, JoshD641 commented on contracts/interfaces/IAuthorizedAccount.sol
> +        uint256 unauthorizedAt; // Block number the permission is started to be unauthorized (block.number + 1)
"Block number at which the permission was last set to authorised" is probably more correct for the first comment. 

For the unauthorised comment, does this mean that the permission is considered to be live during block unauthorisedAt, and not live during block unauthorisedAt +1 ?

2023-06-08 02:28 UTC, JoshD641 commented on contracts/interfaces/IAuthorizedAccount.sol
> +        uint256 authorizedAt; // Block number the main account authorized the authorized account, 0 if not authorized
I can see potential for misunderstand with the phrasing of "0 if not authorised". 

Are you saying that it's 0 if it has never been authorised in the past, or 0 if it is currently not authorised?

Based on the code i think the former is true, but it reads like the latter to me.

2023-06-08 02:28 UTC, JoshD641 commented on test/authorizedAccount.test.ts
> +    let unauthBlock = (await currentBlock()) + 1; // unauthorizeAt = block.number + 1
Is there any way that these two lines could be run during different blocks, leading to unauthBlock being not the same as the unauthBlock in the contract's memory? I'm not sure how the async works with await in this case.

2023-06-08 09:30 UTC, teinnt commented on test/authorizedAccount.test.ts
> +    let unauthBlock = (await currentBlock()) + 1; // unauthorizeAt = block.number + 1
I think it is fine because Hardhat test does not auto mint new block by default, a new block is created when a new transaction is called.

2023-06-11 20:58 UTC, JCSanPedro requested changes

2023-06-11 20:58 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +                        return isAtBlockGreaterThanAuthorizedAt(atBlock, authorizedAt);
I don't think it is good practice to create functions that execute just a condition check, especially since these are only being used once. It means as a reader we would have to verify the function implementation as well. I think it would be more sensisble to use a combination of well named variables and comments to make the code more readable.

```
bool isPermissionUnauthorized = authorizedAt > 0 && authorizedAt < unauthorizedAt;
if (isPermissionUnauthorized) {
  // the permission was previously valid, so we check that
  // the `atBlock` is referencing a time when the permission was valid
  return authorizedAt <= atBlock && atBlock < unauthorizedAt;
}

// Otherwise just check if the permission was authorized before the
// atBlock
return authorizedAt > 0 && authorizedAt <= atBlock;
```

2023-06-11 20:58 UTC, JCSanPedro commented on contracts/interfaces/IAuthorizedAccount.sol
> +        // Block number from which the permission was set to be unauthorised.
```suggestion
        // Block number from which the permission was set to be unauthorized.
```

We should try be consistent for the spelling convnetion

2023-06-12 01:32 UTC, JCSanPedro approved these changes

2023-06-12 01:32 UTC, merged