NET-550 Add-delegated-account
dn3010/sylo-ethereum-contracts pull request #136
Opened 2023-05-17 04:33 UTC by Helenpham1097

## Motivation
As outlined in this here https://www.notion.so/futureverse/RFC-Alleviating-user-friction-in-ticket-creation-process-1b1416776aee4532b513c638ae976e23#1616abd90910416da6fc434fe41e5e0a, we can modify the signature verification check for tickets to rely on a signature from a different wallet, one that has been delegated by the holder of the deposit.

This solution involves:
- Implement new contract to store authorised accounts
- Add additional field in current ticket structure to indicate if the signature is from the main account or a delegated account
- Check permission of the delegated account before withdrawing sender deposit
- Verify signature if delegated account is used in the ticket

## Summary of changes 
- implement authorized account contract
- integrate authorized account contract with ticketing contract
- adding necessary tests

2023-05-17 05:07 UTC, JCSanPedro commented on contracts/interfaces/payments/IAuthorizedAccount.sol
> +// SPDX-License-Identifier: Apache-2.0
I don't think this would be stored under `interfaces/payments` but just `interfaces/payments`. Reason being is that the delegated signature *may* be used for other purposes in the future, so shouldn't be just scoped to payments.

2023-05-19 05:49 UTC, JCSanPedro requested changes
Good job understanding the problem 👍

2023-05-23 00:12 UTC, JCSanPedro requested changes

2023-05-23 00:12 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * new permission at the end of current permissions associated with this authorized account
Btw, wording style for `@notice` docs is more of a high level description of what the function will do, as opposed to a detailed description of the algorithm. It should be written as if it was being explained to an end user (not a dev) https://docs.soliditylang.org/en/v0.8.17/natspec-format.html.

So detailing about where exactly the permission will be stored in the array is not very necessary. I would probably write it something like

```
@notice Adds new permissions to a specific authorized account. This will revert if the authorized account does not exist. Adding existing permissions will have no effect.
```

2023-05-23 00:12 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +    }
This function should also fail if the account does not exist

2023-05-23 00:27 UTC, Helenpham1097 commented on contracts/AuthorizedAccount.sol
> +        }
yeah, you are right, I will change

2023-05-23 05:36 UTC, JCSanPedro reviewed
Just some minor suggestions regarding doc comments, but otherwise looks good. Will assign to @JoshD641 for review.

2023-05-23 05:36 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * @notice Adds new authorized accounts with certain permissions. This will revert if account existed
```suggestion
     * @notice Adds new authorized accounts with certain permissions. This will revert if the account already exists
```

2023-05-23 05:36 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * @notice Removes authorized account of the main account. This will revert if the account
```suggestion
     * @notice Removes an authorized account associated with the msg.sender. This will revert if the account
```

2023-05-23 05:36 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * @param permissions The list of certain permissions that the authorized account
```suggestion
     * @param permissions The list of permissions that the authorized account
```

2023-05-23 05:36 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * can perform in Sylo network
```suggestion
     * can perform within the Sylo network.
```

2023-05-23 05:36 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * does not exist. Removing unexisted permissions will have no effect.
```suggestion
     * does not exist.
```

Probably no need to describe the no-op in this case.

2023-05-23 05:36 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * @notice Validates permission of an authorized account associated with main account
```suggestion
     * @notice Validates permission of an authorized account associated with the main account
```

2023-05-23 05:36 UTC, JCSanPedro commented on contracts/AuthorizedAccount.sol
> +     * @notice Get all authorized accounts of a given main account
```suggestion
     * @notice Get all authorized accounts associated with the given account
```

2023-05-23 05:37 UTC, JCSanPedro reviewed
Just some minor suggestions regarding doc comments, but otherwise looks good. Will assign to @JoshD641 for review.

2023-05-24 02:04 UTC, JoshD641 approved these changes
Looks good to me - the test coverage is thorough, and I can't see any way for the new functionality to be abused in the context of the relay protocol.

2023-05-24 22:14 UTC, JCSanPedro commented
@Helenpham1097 Just double checked the coverage and we're not at 100% anymore. Can you add more testing to bump up the coverage to 100%. On that note we should really add a check to the circle ci workflow to fail if 100% isn't reached.

2023-05-29 03:05 UTC, JCSanPedro approved these changes

2023-05-29 03:05 UTC, merged