NET-580 Use hardhat-deploy to deploy contracts
dn3010/sylo-ethereum-contracts pull request #141
Opened 2023-06-28 02:32 UTC by teinnt

2023-06-28 21:16 UTC, teinnt commented on hardhat.config.ts
> -import '@nomiclabs/hardhat-etherscan';
Remove this based on the instruction https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-toolbox%403.0.0

2023-06-29 01:50 UTC, teinnt commented on hardhat.config.ts
> -import '@openzeppelin/hardhat-upgrades';
Remove this one because we don't use `upgrades` anymore => contract proxy addresses are not saved anymore. It is stated that `hardhat-deploy` saves all deployments scripts [on the disk (git repo)](https://github.com/wighawag/hardhat-deploy) but I don't see it. Should we also saves all deployments by our own?

2023-06-29 04:43 UTC, JCSanPedro requested changes

2023-06-29 04:43 UTC, JCSanPedro commented on deploy/001_deploy_contracts.ts
> +async function saveContracts(
Is there a need for this if `hardhat-deploy` already saves deployments?

2023-06-29 04:43 UTC, JCSanPedro commented on deploy/001_deploy_contracts.ts
> +func.id = 'deploy_contractss'; // id required to prevent reexecution
```suggestion
func.id = 'deploy_contracts'; // id required to prevent reexecution
```

Can you explain the need to do these more? I don't see it in the docs for hardhat-deploy

2023-06-29 04:43 UTC, JCSanPedro commented on deploy/001_deploy_contracts.ts
> +    printEmptyLine();
Seems like you can just add `printEmptyLine` to the `deployContract` fn itself?

2023-06-29 04:43 UTC, JCSanPedro commented on deployments/genesis.config.ts
> +    baseLiveWinProb: (BigInt(2) ** BigInt(128) - BigInt(1)) / BigInt(1000),
I think you can just do

`baseLiveWinProb: (2n ** 128n - 1n) / 1000n`

2023-06-29 04:43 UTC, JCSanPedro commented on hardhat.config.ts
> -import '@openzeppelin/hardhat-upgrades';
Wouldn't it be saved in `./deployments`

2023-06-29 04:45 UTC, teinnt commented on hardhat.config.ts
> -import '@openzeppelin/hardhat-upgrades';
No, it is not automatically saved in `deployments`. I have downloaded the [example repo](https://github.com/wighawag/template-ethereum-contracts)  and run it but it does not save there.

2023-06-29 21:58 UTC, teinnt commented on hardhat.config.ts
> -import '@openzeppelin/hardhat-upgrades';
Ah, it didn't save because I run on network hardhat, otherwise it will be saved.

2023-06-29 23:11 UTC, teinnt commented on deploy/001_deploy_contracts.ts
> +func.id = 'deploy_contractss'; // id required to prevent reexecution
Actually, I copied this from their template. For further explanation: 
```
The function can return true if it wishes to never be executed again. This can be useful to emulate migration scripts that are meant to be executed only once. Once such script return true (async), the id field is used to track execution and if that field is not present when the script return true, it will fails. In other words, if you want a particular deploy script to run only once, it needs to both return true (async) and have an id set.
```
Since we only want to deploy the factory script once, we should set the `id` field right?

2023-06-30 01:31 UTC, teinnt commented on deployments/genesis.config.ts
> +    baseLiveWinProb: (BigInt(2) ** BigInt(128) - BigInt(1)) / BigInt(1000),
OMG

2023-06-30 05:06 UTC, JCSanPedro requested changes
Let's remove the ganache/rata/ropsten deployments since they are not really relevant to us. Otherwise this looks good 👍

2023-07-02 23:15 UTC, teinnt commented
Right, I think we should remove `rata` and `ropsten`, however keep `ganache.json` because the `init_network.ts` needs it to connect to contracts, and `ganache.json` is up-to-date with the current testnet deployment.

2023-07-03 21:32 UTC, JCSanPedro approved these changes
Good work 👍

2023-07-03 21:32 UTC, merged