NET-616 Only update unauthorizedAt if the permission is authorized
dn3010/sylo-ethereum-contracts pull request #143
Opened 2023-07-25 23:39 UTC by teinnt

So far, if the `_removePermissions` is called, we always update the permission's `unauthorizedAt` field even when it is already unauthorized. User would accidentally create a valid period between the first `unauthorizedAt` and the new `unauthorizedAt`. This PR is to fix the issue and only update `unauthorizedAt` if the permission is authorized.

2023-07-27 04:07 UTC, Nick95550 approved these changes
Cool this makes sense to me

2023-07-28 02:45 UTC, JCSanPedro approved these changes
Nice 👍

2023-07-28 02:47 UTC, JCSanPedro requested changes
Actually, the coverage doesn't show that this if statement isn't covered, but I believe we would need to add a specific test for this?

Unless there just happens to be an existing test that coincidentally covers it?

2023-07-28 02:49 UTC, teinnt commented
Yeah, I didn't carefully check, but I remember there are already tests for both cases. I will check it again and let you know.

2023-07-31 23:45 UTC, merged