Create channel contract and update scan function
dn3010/sylo-ethereum-contracts pull request #67
Opened 2022-03-11 04:45 UTC by teinnt

2022-03-13 21:30 UTC, JCSanPedro requested changes
Nice. Looks like you picked things up really fast. I only suggest small changes in the API to allow clients to scan historical directories.

Also is there any tests that need to be updated? I would check that we continue to maintain 100% code coverage as well.

2022-03-13 21:30 UTC, JCSanPedro commented on contracts/Staking/Directory.sol
> +    function hashPoint(uint128 pk, uint8 channel) internal view returns (uint256 point) {
Better name would be `derivePoint` I think. Since the output of this function is the point value itself, and not the hash of the point.

Also `pk` should be probably just be `bytes`, and we should pass in the epochId as a parameter instead of using `currentDirectory`.

2022-03-13 21:30 UTC, JCSanPedro commented on contracts/Staking/Directory.sol
> +    function scan(uint256 point) internal view returns (address stakee) {
I would rename this to `_scan`.

Also I think we should make this function `public`, and have it take in the `epochId` as a parameter. Then in the implementation itself, it should use the specified epochId instead of `currentDirectory` when selecting which directory to scan. This will give the ability for clients to scan using historical directories.

2022-03-15 02:09 UTC, JCSanPedro commented on contracts/Staking/Directory.sol
> +    function _scan(uint256 point, uint256 epochId) public view returns (address stakee) {
I don't think you want to change `uint128 point` to `uint256 point` here

2022-03-15 02:09 UTC, JCSanPedro commented on contracts/Staking/Directory.sol
> +     * @return stakee The address of the node that user will be joined during an epoch.
```suggestion
     * @return stakee The address of the node the user will be assigned to
 ```

2022-03-15 02:09 UTC, JCSanPedro commented on contracts/Staking/Directory.sol
> +    function _scan(uint256 point, uint256 epochId) public view returns (address stakee) {
I think the idea of resting the point value to `uint128` is to prevent overflow when multiplying it with the totalStake of the directory

2022-03-15 02:09 UTC, JCSanPedro commented on test/staking.ts
>      }
Do you think you can add a test for scanning historical epochs?
So basically perform a scan at epoch 1, then initialize the next epoch, then perform a scan for epoch 1 again and check if you get the same results.

2022-03-15 02:12 UTC, JCSanPedro commented
https://961-247604013-gh.circle-artifacts.com/0/~/sylo-ethereum-contracts/coverage/index.html we lost 100% branch coverage for a couple of the files. Can you add tests to make sure we hit it?

On that note, we should probably make circle ci fail if we lose full coverage.

2022-03-16 03:04 UTC, teinnt commented on contracts/Staking/Directory.sol
> +    function _scan(uint256 point, uint256 epochId) public view returns (address stakee) {
Sure

2022-03-16 22:41 UTC, JCSanPedro approved these changes
LGTM

2022-03-16 22:41 UTC, merged