NET-257 Return seeker owner struct instead of owner address
dn3010/sylo-ethereum-contracts pull request #87
Opened 2022-08-24 03:56 UTC by teinnt

Here is link to read the issue: https://github.com/dn3010/go-sylo-node/pull/243#discussion_r953171175

Changes:
- Return `Seekers.Onwer` struct instead of `address` when calling `ownerOf`

2022-08-24 05:20 UTC, JCSanPedro requested changes

2022-08-24 05:20 UTC, JCSanPedro commented on contracts/Seekers.sol
> +            return Owner(address(0), 0);
I think we don't need this `if (owner.owner == address(0))` check anymore. We should return the `owner` value as long as it hasn't expired.

2022-08-25 03:20 UTC, teinnt commented on contracts/Seekers.sol
> +            return Owner(address(0), 0);
Sure

2022-08-25 05:32 UTC, JCSanPedro approved these changes

2022-08-25 05:32 UTC, merged