Net 276 seeker check
dn3010/sylo-ethereum-contracts pull request #92
Opened 2022-09-19 05:34 UTC by JCSanPedro

This PR updates seeker ownership validation to just read from a standard ERC721 contract. This change can be done as we will now expect users to bridge their Seeker from Mainnet to Root.

2022-10-30 22:40 UTC, teinnt commented on contracts/Registries.sol
> +        require(end > start, "end index must be greater than start index");
No a review but I found this when implementing my feature. Do we allow getting exactly one registry? I.e. start = 1 and end = 1?

2022-10-31 21:28 UTC, teinnt reviewed
Just a little more to change, otherwise looking good to me.

2022-10-31 21:28 UTC, teinnt commented on contracts/Registries.sol
> +    function getTotalNodes() external view returns (uint256) {
Should we name it to `getNodesCount()`?

2022-10-31 21:28 UTC, teinnt commented on contracts/TestSeekers.sol
> +}
Maybe we need to add one more line at the end.

2022-10-31 21:28 UTC, teinnt commented on contracts/Registries.sol
> +        require(end > start, "end index must be greater than start index");
I think we should use uppercase to make it consistent with other error messages.

```suggestion
        require(end > start, "End index must be greater than start index");
```

2022-10-31 21:28 UTC, teinnt commented on contracts/Registries.sol
> +            "end index cannot be greater than total number of registered nodes"
```suggestion
            "End index cannot be greater than total number of registered nodes"
```

2022-10-31 21:28 UTC, teinnt commented on contracts/Registries.sol
> +    function getTotalNodes() external view returns (uint256) {
I think we can name it to `getNodesCount()`

2022-10-31 21:28 UTC, teinnt commented on test/registries.ts
> +      'end index must be greater than start index',
```suggestion
      'End index must be greater than start index',
```

2022-10-31 21:28 UTC, teinnt commented on test/registries.ts
> +      'end index cannot be greater than total number of registered nodes',
```suggestion
      'End index cannot be greater than total number of registered nodes',
```

2022-11-24 21:49 UTC, JoshD641 requested changes
Looks good to me - just a few comments about naming and more specific error messages for UX, nothing major.

2022-11-24 21:49 UTC, JoshD641 commented on contracts/Epochs/Manager.sol
> +    IERC721 public _rootSeekers;
Tiny detail, but I can see the name rootSeekers being confusing if we're ever running this on something other than root network. 

Maybe bridgedSeekers instead? That way it's still clear that they're on the same blockchain as the contracts, and that the data structure contains only the subset of the seekers that have been bridged.

2022-11-24 21:49 UTC, JoshD641 commented on contracts/Registries.sol
> +        address owner = _rootSeekers.ownerOf(seekerId);
What does ownerOf(seekerID) return when the specified seeker hasn't been bridged? 

We could explicitly handle that case, separately from "sorry, the owners don't match", so that the dashboard UI can give a more helpful error message.

2022-11-24 23:16 UTC, JCSanPedro commented on contracts/Registries.sol
> +        address owner = _rootSeekers.ownerOf(seekerId);
It is address zero, but it could potentially be transferred (burned) to that address. I guess that would be an odd edge case though

2022-11-24 23:17 UTC, JCSanPedro commented on contracts/Epochs/Manager.sol
> +    IERC721 public _rootSeekers;
It might be just better to call it `_seekers` in this case (maybe we will be on Eth mainnet :P)

2022-11-24 23:26 UTC, JoshD641 commented on contracts/Registries.sol
> +        address owner = _rootSeekers.ownerOf(seekerId);
Yea, that does seem unlikely to me. 

I think interpreting "owned by address zero" as "not bridged" is better UX wise than interpreting "not bridged" as "you don't own that seeker", though that assumption should probably be made in the dashboard rather than the contracts. If we just return an error "Owned by address 0", the contracts can be unambiguous, and the dashboard can interpret that how it wants.

2022-11-24 23:31 UTC, JoshD641 approved these changes

2022-11-25 01:32 UTC, JCSanPedro commented on contracts/Registries.sol
> +        address owner = _rootSeekers.ownerOf(seekerId);
Yeah the dashboard shouldn't. get into this case because it only shows seekers owned by the user, so it wouldn't register a seeker not owned by the user anyway.

2022-11-27 20:16 UTC, JCSanPedro commented on contracts/Registries.sol
> +    function getTotalNodes() external view returns (uint256) {
Not really a significant difference between either of these names, but just personally prefer the world `total` over `count`

2022-11-28 21:19 UTC, teinnt approved these changes
Awesome! LGTM.

2022-11-28 21:23 UTC, merged