NET77-Local-rootnet-docker
dn3010/sylo-ethereum-contracts pull request #94
Opened 2022-11-08 20:57 UTC by teinnt

2022-12-01 01:37 UTC, JCSanPedro requested changes
Cool, just some minors otherwise looks good.

Thank you for also updating the `scripts` files to be typescript.

2022-12-01 01:37 UTC, JCSanPedro commented on deploy/00_deploy_phase_two.ts
> +  let tx = await registries.initialize(
Don't really like using the `let` keyword in general but I see why you used it here. Anyway, if we just need the tx variable to call `tx.wait()`, we can do this instead
```
await registries.initialize(....).then(tx => tx.wait());
```

2022-12-01 01:37 UTC, JCSanPedro commented on deploy/00_deploy_phase_two.ts
> +  if (config.Seekers.shouldMint) {
I don't like this being part of the deployment script. I think for testnets, we can just define another javascript file to run the code to do the minting, as opposed to this conditional check.

2022-12-01 01:37 UTC, JCSanPedro commented on deploy/genesis.config.ts
> +    unlockDuration: 30, // 150 seconds
Let's revert the changes to these parameters when merging into `master`. We can keep it for `deploy-contracts`, as that is the branch we use for testing, but not for `master`.

2022-12-01 01:37 UTC, JCSanPedro commented on docker/rootnet-with-protocol/README.md
> +The `private key` used to when starting the node and also
```suggestion
The `private key` used when starting the node and also
```

2022-12-01 01:37 UTC, JCSanPedro commented on scripts/contract_interaction.ts
> +main();
What's the point of this file? I think any like utility scripts we can keep in our `sylo-ethereum-utils` repo

2022-12-01 04:31 UTC, teinnt commented on scripts/contract_interaction.ts
> +main();
Oh yeah, it is for me to test contract methods. I will remove it.

2022-12-05 01:19 UTC, JCSanPedro approved these changes

2022-12-05 01:20 UTC, merged