NET-346 Amend behaviour in `setRegistry` to automatically revoke seekers that have already been registered
dn3010/sylo-ethereum-contracts pull request #97
Opened 2022-12-14 02:03 UTC by Nick95550

## Motivation
It is possible to register the same seeker multiple times as long as it is owned by the specified seeker account.
This can lead to confusion where there exists more than one Registry with the same seeker Id. It is better to remove
this so that a single seeker can only be registered in a single registry at a time.

## Summary of changes
A new mapping in the Registries contract keeps track of the seeker account associated with the seeker ID.
Using this mapping, when a seeker is transferred from one account to another and registered the old registry has its seeker Id field reset.

To test this a new test case has been written and implemented that mints a seeker, transfers it and ensures that the old registry is successfully cleared. 

A call to revokeSeekerAccount also resets this new mapping 

## Checklist

- [X] Updated the readme documents (`README.md` etc.)
- [X] Updated `CHANGELOG.md` with new items at top of list

### Local Build

- [X] Run npm run test

2022-12-14 23:30 UTC, JCSanPedro requested changes

2022-12-14 23:30 UTC, JCSanPedro commented on deploy/hardhat_deployment_phase_two.json
> +}
No need to track this file in our repo

2022-12-14 23:30 UTC, JCSanPedro commented on deploy/nikau_deployment_phase_two.json
> +}
Again, this change is inconsequential but still unrelated.

2022-12-14 23:30 UTC, JCSanPedro commented on test/registries.ts
> +  it("Doesn't exists that more than one Registry has same seeker ID", async() => {
```suggestion
  it("can't register a seeker using the same seeker ID", async() => {
```

2022-12-14 23:30 UTC, JCSanPedro commented on test/registries.ts
> +    const proofMessage = `${proofMessagePrefix}:${tokenID}:${seekerAddressLower}:${blockString}`;
Can we just reuse this function when setting the seeker https://github.com/dn3010/sylo-ethereum-contracts/blob/master/test/utils.ts#L160?

2022-12-14 23:30 UTC, JCSanPedro commented on test/registries.ts
> +    // Tests that the registry for both seekers accounts has the same seekerID (BAD, NEED TO FIX)!!!!!
Does this comment need to be updated?

2022-12-14 23:30 UTC, JCSanPedro commented on test/registries.ts
> +    */
Multi-line comments using `/* ... *../` are usually reserved for function documentation

2022-12-14 23:30 UTC, JCSanPedro commented on contracts/Registries.sol
> +        seekerRegistration[registry.seekerId] = address(0);
I think we can also add in here
`registry.seekerId = 0`

2022-12-14 23:30 UTC, JCSanPedro commented on contracts/Registries.sol
> +        seekerRegistration[seekerId] = seekerAccount;
I think this needs to be
`seekerRegistration[seekerId] = msg.sender;`.

The `seekerAccount` represent's the node runner's personal account. `msg.sender` represents the node's own account as this function will be sent from the itself.

A node runner can run multiple nodes but their seeker should be associated with only one node account (`msg.sender`) at any given time.

2022-12-14 23:32 UTC, JCSanPedro commented
Good job learning all the typescript/nodejs/ethers.js stuff!

2022-12-16 00:04 UTC, JCSanPedro requested changes
Looks good, just a couple nitpicky comments I've left.

Also, I see in this PR you have deleted `.openzeppelin/ropsten.json` and `deploy/nikau_deploy_phase_two.json`. Since deleting those files are unrelated to the PR, we *shouldn't* include, but because we kind of need to remove them anyway, I'll allow this time around.

2022-12-16 01:59 UTC, Nick95550 commented on test/staking.ts
> +      await addStakeAndJoinEpoch(accounts[i], amountEpochTwo[i], i + seekerIdOffset);
Yea but I believe the problem is that the same seeker ID is being used in the previous loop here https://github.com/dn3010/sylo-ethereum-contracts/blob/master/test/staking.ts#L644. So this will register a different seeker to the account.

2022-12-16 04:41 UTC, JCSanPedro commented on test/staking.ts
> +      await addStakeAndJoinEpoch(accounts[i], amountEpochTwo[i], i + seekerIdOffset);
I don't think that problem is happening because this loop is for joining the next epoch (and no seekers are in use for the next epoch). Also, it wouldn't make sense anyway since you're only adding `1` to the iteration value, so some of the seeker ids would be reused.

I just checked out the code. It's actually a bug in the logic. If the same node registers with the same seeker Id twice, then when it hits this line in the code
`registries[seekerRegistration[seekerId]].seekerId = 0;`
It basically sets its own registries seekerId to 0.

2022-12-18 20:35 UTC, Nick95550 commented on test/staking.ts
> +      await addStakeAndJoinEpoch(accounts[i], amountEpochTwo[i], i + seekerIdOffset);
Yea I suppose I hadn't thought that the account would set the same seeker twice in a row, so implemented this work around that would ensure that a different seeker is set to the same account during testing. I'll change the logic now using your suggestion.

2022-12-19 01:35 UTC, JCSanPedro approved these changes

2022-12-19 03:40 UTC, teinnt reviewed
Well done! Only some small things left and this PR is ready.

2022-12-19 03:40 UTC, teinnt commented on test/registries.ts
> +  it("can't register a seeker using the same seeker ID", async() => {
I think we _can_ register a seeker using the same seeker ID, because there is no error in the code. Should we say 

```suggestion
  it("registered node seeker id will be reset if a new node registers with the same seeker id", async() => {
```

2022-12-19 03:40 UTC, teinnt commented on test/registries.ts
> +    const accountAddress = await account.getAddress();
Should we name them `accountOne` and `accountAddressOne` so it is more readable and easier to compare? I think would be good to update `regoSeekerAccount` to `regoSeekerAccountOne` too.

2022-12-19 03:40 UTC, teinnt commented on test/registries.ts
> +    await utils.setSeekerRegistry(registries, seekers, accountTwo, seekerAccount, tokenID);
Hmmm, I am not sure if you use prettier, can you check if you have it installed and enabled? As this is the format we should have with prettier (it auto formatted when I pressed Command+S). Can you try to run this command `npx prettier ./test --write`?

![Screen Shot 2022-12-19 at 4 33 10 PM](https://user-images.githubusercontent.com/61264574/208342253-a9d729d7-5034-497f-98cd-3f5a3f7969ba.png)

2022-12-19 03:40 UTC, teinnt commented on test/registries.ts
> +    expect(regoSeekerAccount.seekerId).not.equal(regoSeekerAccountTwo.seekerId);
Do you think we need this check, because if other checks pass (comparing with 0 and 100), then we know they are not equal right?

2022-12-19 03:40 UTC, teinnt commented on test/registries.ts
> +    expect(regoSeekerAccountTwo.seekerId).is.equal(100);
```suggestion
    expect(regoSeekerAccountTwo.seekerId).is.equal(tokenID);
```

2022-12-19 03:40 UTC, teinnt commented on contracts/Registries.sol
> +        registry.seekerId = 0;
Not necessary, but we can change it like this so it is more readable and consistent with the order we have in `setSeekerAccount`.

```suggestion
        registry.seekerId = 0;
        registry.seekerAccount = address(0);

        seekerRegistration[registry.seekerId] = address(0);
```

2022-12-19 20:50 UTC, Nick95550 commented on test/registries.ts
> +  it("can't register a seeker using the same seeker ID", async() => {
Yea that is a better description I think

2022-12-19 20:54 UTC, Nick95550 commented on test/registries.ts
> +    await utils.setSeekerRegistry(registries, seekers, accountTwo, seekerAccount, tokenID);
This command didn't do anything for me, I think I have prettier installed though.

2022-12-19 22:13 UTC, Nick95550 commented on contracts/Registries.sol
> +        registry.seekerId = 0;
I think that making this change will produce a bug in the logic, as the registry.seekerId will be set to zero before it is used in the seekerRegistration mapping

2022-12-19 22:29 UTC, teinnt commented on contracts/Registries.sol
> +        registry.seekerId = 0;
Right, my bad. Thanks Nic!

2022-12-19 22:30 UTC, teinnt approved these changes
LGTM

2022-12-19 23:06 UTC, JCSanPedro approved these changes

2022-12-19 23:07 UTC, merged